### ISSUE TITLE
Admin > Setting > General > Product Line

### ISSUE THREAD

**Issue by gusindra** [gusindra/hireach#134]
![image](https://github.com/user-attachments/assets/854ddf94-5948-4efd-806b-bd4dfea98a40)
Error saat delete product line, muncul blank page saat berhasil terupload

**Comment by ardanayatraa** [comment]
![image](https://github.com/user-attachments/assets/7c37df4d-134d-462d-a545-93695dcd943d)

Bisa delete product Line tanpa error
