### ISSUE TITLE
Improvement - Order Admin Side

### ISSUE THREAD

**Issue by ardanayatraa** [gusindra/hireach#80]
- top up user from admin , no have order product (tax) , make same like topup from user

**Comment by ardanayatraa** [comment]
Fixed Bug Perhitungan [commamnd create TAX  in Top Up User]

**Comment by gusindra** [comment]
yg improvement untuk buat order flow nya sama seperti yg buat order pada user apakah sudah di tambahkan juga ? @ardanayatraa 

jadi nanti otomatis tax nya seperti yg di order topup.. ?

solusinya bisa di buatkan pilihan jika admin buat otder typenya topup balance makan nanti flownya sama seperti yg ada pada user. jadi livewire di User Panel copy ke Admin Panel, terus di tambahkan settingan untuk pilih usernya

**Comment by gusindra** [comment]
Update Improvement:
1.
![image](https://github.com/user-attachments/assets/d4da1698-d9a7-4947-9e74-bc468f7d8bef)
jika order di buat dari user maka vat dibuat default 0 karena sudah included pada item order

2. 
![image](https://github.com/user-attachments/assets/92b84324-c59f-47f5-bada-a368c04860b7)
pada bagian customer information di buat seragam menggunakan client uuid, yg sekarang masih ada yg menggunakan user_id
![image](https://github.com/user-attachments/assets/4afc6970-2556-423b-84a8-31804457fd1d)

3.
![image](https://github.com/user-attachments/assets/77774b52-e143-4719-b3e1-592cb48d3275)
saat order topup di submit oleh admin maka seharusnya akan muncul di bagian topup menunggu pembayaran di user panel

coba di update dulu 3 point di atas ya @ardanayatraa

**Comment by ardanayatraa** [comment]
> Update Improvement: 1. ![image](https://private-user-images.githubusercontent.com/4585382/348032491-d4da1698-d9a7-4947-9e74-bc468f7d8bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDE2NjgsIm5iZiI6MTcyMDc0MTM2OCwicGF0aCI6Ii80NTg1MzgyLzM0ODAzMjQ5MS1kNGRhMTY5OC1kOWE3LTQ5NDctOWU3NC1iYzQ2OGY3ZDhiZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMjM0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRjNWY4YjlmNTU1YzBjYmQ5YmFhODdkZTBjYzhlYzg5OGQ3NWQxYWIyOTQ2NjIxOTk4NzIzYzBjNzNlN2MyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F9KimZnx65_3KdPYLYUogNMBho_fsq2c9Z-VhfIRLq0) jika order di buat dari user maka vat dibuat default 0 karena sudah included pada item order
> 
> 
> ![image](https://private-user-images.githubusercontent.com/4585382/348033027-92b84324-c59f-47f5-bada-a368c04860b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDE2NjgsIm5iZiI6MTcyMDc0MTM2OCwicGF0aCI6Ii80NTg1MzgyLzM0ODAzMzAyNy05MmI4NDMyNC1jNTlmLTQ3ZjUtYmFkYS1hMzY4YzA0ODYwYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMjM0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE0NmQ5ZmI5NTdmYzJhMmQwY2MyNWVlN2IwZWViNGYzNjQ3ZjAzZTNhMDhmNDBlMjRjMzc3YWI2OTUzOGVmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m5I7gu4pKgRJNyYxmygXmGy2M3xGxZfb99jQ179e548) pada bagian customer information di buat seragam menggunakan client uuid, yg sekarang masih ada yg menggunakan user_id ![image](https://private-user-images.githubusercontent.com/4585382/348033973-4afc6970-2556-423b-84a8-31804457fd1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDE2NjgsIm5iZiI6MTcyMDc0MTM2OCwicGF0aCI6Ii80NTg1MzgyLzM0ODAzMzk3My00YWZjNjk3MC0yNTU2LTQyM2ItODRhOC0zMTgwNDQ1N2ZkMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMjM0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYxOTkxMDhmMGNhY2VkYTVjYjU2NWFkMmQxNzFmMjMzNmRmYWVjNzZiOGY2NjY5OTYzOTBiNmQ1NTYyMTMyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.13FVDPlMLY1bbD1QgxmFwYvF6rwnwNMJRhAH3fwkVOo)
> 
> 
> ![image](https://private-user-images.githubusercontent.com/4585382/348035336-77774b52-e143-4719-b3e1-592cb48d3275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDE2NjgsIm5iZiI6MTcyMDc0MTM2OCwicGF0aCI6Ii80NTg1MzgyLzM0ODAzNTMzNi03Nzc3NGI1Mi1lMTQzLTQ3MTktYjNlMS01OTJjYjQ4ZDMyNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMjM0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkxYWRiN2Y4ZWYyNGFkYWVlZWRlMTk3ZGM3YjRiOWU4N2JjMTkyNjFjZjFjYjQyNzBkOTQ3ZGFiNWVhNzE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.neDDNWVpHZYQXNJtPB8MUfJWe2Gxudhs9kVHvQ2AJpc) saat order topup di submit oleh admin maka seharusnya akan muncul di bagian topup menunggu pembayaran di user panel
> 
> coba di update dulu 3 point di atas ya @ardanayatraa

baik pak

**Comment by gusindra** [comment]
tambahan di bagian user panel Order Invoicenya masih salah perhitungannya:
![image](https://github.com/user-attachments/assets/d0e5bbd2-b381-40ab-8201-b319d8aa7fc3)
@ardanayatraa

**Comment by ardanayatraa** [comment]
> tambahan di bagian user panel Order Invoicenya masih salah perhitungannya: ![image](https://private-user-images.githubusercontent.com/4585382/348045087-d0e5bbd2-b381-40ab-8201-b319d8aa7fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDI1ODYsIm5iZiI6MTcyMDc0MjI4NiwicGF0aCI6Ii80NTg1MzgyLzM0ODA0NTA4Ny1kMGU1YmJkMi1iMzgxLTQwYWItODIwMS1iMzE5ZDhhYTdmYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMjM1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU0Y2E3MGMxOTc4MThhZGMyZWFkMTBiMTQ2Y2Y4NGIyOTgxMDVlZWI5NDZiZmIyYzZmYjFmNmRjNGZhZTAzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NggzlAjTuiktq1aruc-lf3qNgVS1z_p8Z6ITL_EXHJc) @ardanayatraa

Baik pak

**Comment by gusindra** [comment]
- View invoice di user dan admin masih salah
![image](https://github.com/user-attachments/assets/1566dfba-5133-4ba6-a4db-f3e2fd828cad)

- View topup di user masih salah
![image](https://github.com/user-attachments/assets/7298655b-3e72-48da-8608-83c20f9ddffb)
![image](https://github.com/user-attachments/assets/ca6ea400-970a-4736-9146-74a97cf29071)

**Comment by ardanayatraa** [comment]
![image](https://github.com/user-attachments/assets/b069a667-7750-447d-a057-baafd95523c4)
Di buat reactive ,
