### ISSUE TITLE
Security Request

### ISSUE THREAD

**Issue by gusindra** [gusindra/hireach#88]
check all url access request using filterInput and strip tag php
![image](https://github.com/user-attachments/assets/f9576ad2-e003-4099-bd4a-109d7040e3c6)

**Comment by gusindra** [comment]
di request API juga ya di tambahkan filter nya ya

**Comment by ardanayatraa** [comment]
Template, Contact, Profile, Team, Chat, Resource, Campaign, Api One Way , Api Two Way,Register, Login,Reset Pass
